// <auto-generated />
using System;
using AspireAstro.WebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireAstro.WebApi.Migrations
{
    [DbContext(typeof(AstroDbContext))]
    partial class AstroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireAstro.WebApi.Database.BlogViews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BlogViews");
                });
#pragma warning restore 612, 618
        }
    }
}
